#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=10

start_service()
{
	config_load onu_watchdog
	config_get_bool enabled main enabled 1
	[ "$enabled" -eq 1 ] || return 0

	procd_open_instance
	procd_set_param command /usr/sbin/onu-watchdog daemon
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers()
{
	procd_add_reload_trigger onu_watchdog network
}

reload_service()
{
	stop
	start
}
